drop table if exists account;
/
create table if not exists account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acct_nbr TEXT not null,
    acct_code TEXT null,
    acct_name TEXT null,
    create_ts timestamptz null,
    update_ts timestamptz default now()
);
/
ALTER TABLE account
ADD CONSTRAINT unique_acct_nbr UNIQUE (acct_nbr);
/
DROP INDEX IF EXISTS idx_account_fac_code;
/
CREATE INDEX idx_account_acct_nbr ON account(acct_nbr) INCLUDE(acct_name);
/
DROP INDEX IF EXISTS idx_account_update_ts;
/
CREATE INDEX idx_account_update_ts ON account(update_ts);
/
DROP INDEX IF EXISTS idx_account_create_ts;
/
CREATE INDEX idx_account_create_ts ON account(create_ts);
/