drop table if exists log;
/
create table if not exists log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level TEXT,
    message TEXT,
    file_name TEXT,
    line_number bigint,
    create_ts timestamptz null
);
/
DROP INDEX IF EXISTS idx_log_create_ts;
/
CREATE INDEX idx_log_create_ts ON log(create_ts);
/
DROP INDEX IF EXISTS idx_log_message_level;
/
CREATE INDEX idx_log_message_level ON log(message, level);
/