drop table if exists index_override;
/
create table if not exists index_override (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain TEXT not null,
    index_source_ts timestamptz not null,
    index_target_ts timestamptz not null,
    create_ts timestamptz default now()
);
/
ALTER TABLE index_override
ADD CONSTRAINT unique_domain UNIQUE (domain);
/
drop table if exists index_override_history;
/
create table if not exists index_override_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain TEXT not null,
    index_source_ts timestamptz not null,
    index_target_ts timestamptz not null,
    create_ts timestamptz default now()
);