drop table if exists account;
/
create table if not exists account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_nbr TEXT not null,
    account_code TEXT null,
    account_name CITEXT null,
    create_ts timestamptz null,
    update_ts timestamptz default now()
);
/
ALTER TABLE account
ADD CONSTRAINT unique_account_nbr UNIQUE (account_nbr);
/
DROP INDEX IF EXISTS idx_account_account_nbr;
/
CREATE INDEX idx_account_account_nbr ON account(account_nbr) INCLUDE(account_name);
/
DROP INDEX IF EXISTS idx_account_update_ts;
/
CREATE INDEX idx_account_update_ts ON account(update_ts);
/
DROP INDEX IF EXISTS idx_account_create_ts;
/
CREATE INDEX idx_account_create_ts ON account(create_ts);
/