drop table if exists userfacility;
/
create table if not exists userfacility (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    facility_id BIGINT NOT NULL,
    create_ts timestamptz null,
    update_ts timestamptz default now()
);
/
ALTER TABLE userfacility 
ADD CONSTRAINT unique_userfacility_id UNIQUE (user_id, facility_id);
/
DROP INDEX IF EXISTS idx_userfacility_user_id;
/
CREATE INDEX idx_userfacility_user_id ON userfacility(user_id);
/
DROP INDEX IF EXISTS idx_userfacility_update_ts;
/
CREATE INDEX idx_userfacility_update_ts ON userfacility(update_ts);
/
DROP INDEX IF EXISTS idx_userfacility_update_ts;
/
CREATE INDEX idx_userfacility_update_ts ON userfacility(create_ts);
/