drop table if exists service;
/
create table if not exists service (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT not null,
    svc_nbr TEXT not null,
    svc_code TEXT not null,
    svc_name TEXT null,
    status_code CITEXT not null default 'UNKNOWN',
    create_ts timestamptz null,
    update_ts timestamptz default now()
);
/
ALTER TABLE service
ADD CONSTRAINT unique_svc_nbr UNIQUE (svc_nbr);
/
DROP INDEX IF EXISTS idx_service_svc_code;
/
CREATE INDEX idx_service_svc_code ON service(svc_code, status_code) INCLUDE (svc_name);
/
DROP INDEX IF EXISTS idx_service_update_ts;
/
CREATE INDEX idx_service_update_ts ON service(update_ts);
/
DROP INDEX IF EXISTS idx_service_create_ts;
/
CREATE INDEX idx_service_create_ts ON service(create_ts);
/