drop table if exists event_notification_buffer;
/
CREATE TABLE if not exists event_notification_buffer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel TEXT NOT NULL,
    payload TEXT NOT NULL,
    create_ts TIMESTAMPTZ DEFAULT NOW()
);
/
DROP INDEX IF EXISTS idx_event_notification_buffer_payload;
/
CREATE INDEX idx_event_notification_buffer_payload ON event_notification_buffer(payload);
/
DROP INDEX IF EXISTS idx_event_notification_buffer_create_ts;
/
CREATE INDEX idx_event_notification_buffer_create_ts ON event_notification_buffer(create_ts);
/