drop table if exists service;
/
create table if not exists service (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT not null,
    service_nbr TEXT not null,
    service_code TEXT null,
    service_name TEXT null,
    status_code CITEXT not null default 'UNKNOWN',
    create_ts timestamptz null,
    update_ts timestamptz default now()
);
/
ALTER TABLE service
ADD CONSTRAINT unique_service_nbr UNIQUE (service_nbr);
/
DROP INDEX IF EXISTS idx_service_service_code;
/
CREATE INDEX idx_service_service_code ON service(service_code, status_code) INCLUDE (service_name);
/
DROP INDEX IF EXISTS idx_service_update_ts;
/
CREATE INDEX idx_service_update_ts ON service(update_ts);
/
DROP INDEX IF EXISTS idx_service_create_ts;
/
CREATE INDEX idx_service_create_ts ON service(create_ts);
/