insert into facility (acct_id, fac_nbr, fac_code, fac_name, create_ts) values (1, 'FAC_NBR_01','US_TEST_01', 'TEST FACILITY 1', now());
insert into facility (acct_id, fac_nbr, fac_code, fac_name, create_ts) values (2, 'FAC_NBR_02','US_TEST_02', 'TEST FACILITY 2', now());
insert into facility (acct_id, fac_nbr, fac_code, fac_name, create_ts) values (3, 'FAC_NBR_03','US_TEST_03', 'TEST FACILITY 3', now());
insert into facility (acct_id, fac_nbr, fac_code, fac_name, create_ts) values (4, 'FAC_NBR_04','US_TEST_04', 'TEST FACILITY 4', now());
insert into facility (acct_id, fac_nbr, fac_code, fac_name, create_ts) values (5, 'FAC_NBR_05','US_TEST_05', 'TEST FACILITY 5', now());
insert into facility (acct_id, fac_nbr, fac_code, fac_name, create_ts) values (6, 'FAC_NBR_06','US_TEST_06', 'TEST FACILITY 6', now());
insert into facility (acct_id, fac_nbr, fac_code, fac_name, create_ts) values (7, 'FAC_NBR_07','US_TEST_07', 'TEST FACILITY 7', now());
insert into facility (acct_id, fac_nbr, fac_code, fac_name, create_ts) values (8, 'FAC_NBR_08','US_TEST_08', 'TEST FACILITY 8', now());
insert into facility (acct_id, fac_nbr, fac_code, fac_name, create_ts) values (9, 'FAC_NBR_09','US_TEST_09', 'TEST FACILITY 9', now());
insert into facility (acct_id, fac_nbr, fac_code, fac_name, create_ts) values (10, 'FAC_NBR_10','US_TEST_10', 'TEST FACILITY 10', now());
insert into facility (acct_id, fac_nbr, fac_code, fac_name, create_ts) values (1, 'FAC_NBR_11','US_TEST_11', 'TEST FACILITY 11', now());
insert into facility (acct_id, fac_nbr, fac_code, fac_name, create_ts) values (2, 'FAC_NBR_12','US_TEST_12', 'TEST FACILITY 12', now());
insert into facility (acct_id, fac_nbr, fac_code, fac_name, create_ts) values (3, 'FAC_NBR_13','US_TEST_13', 'TEST FACILITY 13', now());
insert into facility (acct_id, fac_nbr, fac_code, fac_name, create_ts) values (4, 'FAC_NBR_14','US_TEST_14', 'TEST FACILITY 14', now());
insert into facility (acct_id, fac_nbr, fac_code, fac_name, create_ts) values (5, 'FAC_NBR_15','US_TEST_15', 'TEST FACILITY 15', now());
insert into facility (acct_id, fac_nbr, fac_code, fac_name, create_ts) values (6, 'FAC_NBR_16','US_TEST_16', 'TEST FACILITY 16', now());
insert into facility (acct_id, fac_nbr, fac_code, fac_name, create_ts) values (7, 'FAC_NBR_17','US_TEST_17', 'TEST FACILITY 17', now());
insert into facility (acct_id, fac_nbr, fac_code, fac_name, create_ts) values (8, 'FAC_NBR_18','US_TEST_18', 'TEST FACILITY 18', now());
insert into facility (acct_id, fac_nbr, fac_code, fac_name, create_ts) values (9, 'FAC_NBR_19','US_TEST_19', 'TEST FACILITY 19', now());
insert into facility (acct_id, fac_nbr, fac_code, fac_name, create_ts) values (10, 'FAC_NBR_20','US_TEST_20', 'TEST FACILITY 20', now());

insert into facility (id, acct_id, fac_nbr, fac_code, fac_name, create_ts) values (-99, -99, 'UNKNOWN', 'UNKNOWN', 'UNKNOWN', now());
insert into facility (id, acct_id, fac_nbr, fac_code, fac_name, create_ts) values (-1, -1, 'ALL', 'ALL', 'ALL', now());
