drop table if exists asset;
/
create table if not exists asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fac_id int not null,
    asset_nbr varchar(250) not null,
    sys_id varchar(250) null,
    status_code varchar(50) not null default 'UNKNOWN',
    create_ts timestamptz,
    update_ts timestamptz default now()
);
/
ALTER TABLE asset
ADD CONSTRAINT unique_asset_nbr UNIQUE (asset_nbr);
/