drop table if exists event_notification_buffer;
/
CREATE TABLE if not exists event_notification_buffer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel VARCHAR(250) NOT NULL,
    payload VARCHAR(250) NOT NULL,
    create_ts TIMESTAMPTZ DEFAULT NOW()
);
/