drop table if exists last_index;
/
create table if not exists last_index (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain TEXT not null,
    last_index_ts timestamptz null,
    index_target_ts timestamptz null,
    update_ts timestamptz default now()
);
/