drop table if exists index_log;
/
create table if not exists index_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_name varchar(250) not null,
    status varchar(250) null,
    description text null,
    create_ts timestamptz null,
    update_ts timestamptz default now()
);
/
DROP INDEX IF EXISTS idx_index_log_update_ts;
/
CREATE INDEX idx_index_log_update_ts ON index_log(update_ts);
/
DROP INDEX IF EXISTS idx_index_log_create_ts;
/
CREATE INDEX idx_index_log_create_ts ON index_log(create_ts);
/