-- This table is currently not used.  We are using the facility_facility table
-- which is controled by Django migrations.
drop table if exists daas.facility;
/
create table if not exists daas.facility (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fac_code varchar(250) not null,
    fac_name varchar(250) null,
    create_ts timestamptz null,
    update_ts timestamptz default now()
);
/
