drop table if exists account;
/
create table if not exists account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acct_code varchar(250) not null,
    acct_name varchar(250)null,
    create_ts timestamptz null,
    update_ts timestamptz default now()
);
/
DROP INDEX IF EXISTS idx_account_fac_code;
/
CREATE INDEX idx_account_fac_code ON account(acct_code) INCLUDE(acct_name);
/
DROP INDEX IF EXISTS idx_account_update_ts;
/
CREATE INDEX idx_account_update_ts ON account(update_ts);
/
DROP INDEX IF EXISTS idx_account_create_ts;
/
CREATE INDEX idx_account_create_ts ON account(create_ts);
/