-- This table is managed by Django, but we update it here for src and build.
drop table if exists daas.facility_facility;
/
CREATE TABLE daas.facility_facility (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	fac_code varchar(250) NOT NULL,
	"name" varchar(250) NOT NULL,
	address text NULL,
	phone_number varchar(15) NULL,
	create_ts timestamptz NULL,
	update_ts timestamptz NULL default now(),
	CONSTRAINT facility_facility_fac_code_key UNIQUE (fac_code)
);
/
CREATE INDEX facility_facility_fac_code ON daas.facility_facility USING btree (fac_code varchar_pattern_ops);
/