drop table if exists service;
/
create table if not exists service (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT not null,
    service_code varchar(250) not null,
    service_name varchar(250) null,
    status_code varchar(50) not null default 'UNKNOWN',
    create_ts timestamptz null,
    update_ts timestamptz default now()
);
/
