drop table if exists daas.account;
/
create table if not exists daas.account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acct_code varchar(250) not null,
    acct_name varchar(250)null,
    create_ts timestamptz null,
    update_ts timestamptz default now()
);
/
